// <auto-generated />
using Livraria.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Livraria.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260121203035_CreateViewRelatorioLivrosPorAutor")]
    partial class CreateViewRelatorioLivrosPorAutor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Livraria.Domain.Entities.Assunto", b =>
                {
                    b.Property<int>("CodAs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CodAs");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodAs"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Descricao");

                    b.HasKey("CodAs");

                    b.ToTable("Assunto", (string)null);
                });

            modelBuilder.Entity("Livraria.Domain.Entities.Autor", b =>
                {
                    b.Property<int>("CodAu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CodAu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodAu"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("Nome");

                    b.HasKey("CodAu");

                    b.ToTable("Autor", (string)null);
                });

            modelBuilder.Entity("Livraria.Domain.Entities.FormaCompra", b =>
                {
                    b.Property<int>("CodFc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CodFc");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodFc"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Descricao");

                    b.HasKey("CodFc");

                    b.ToTable("FormaCompra", (string)null);
                });

            modelBuilder.Entity("Livraria.Domain.Entities.Livro", b =>
                {
                    b.Property<int>("CodL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CodL");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodL"));

                    b.Property<string>("AnoPublicacao")
                        .IsRequired()
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("AnoPublicacao");

                    b.Property<int>("Edicao")
                        .HasColumnType("int")
                        .HasColumnName("Edicao");

                    b.Property<string>("Editora")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("Editora");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("Titulo");

                    b.HasKey("CodL");

                    b.ToTable("Livro", (string)null);
                });

            modelBuilder.Entity("Livraria.Domain.Entities.LivroAssunto", b =>
                {
                    b.Property<int>("Livro_CodL")
                        .HasColumnType("int")
                        .HasColumnName("Livro_CodL");

                    b.Property<int>("Assunto_CodAs")
                        .HasColumnType("int")
                        .HasColumnName("Assunto_CodAs");

                    b.HasKey("Livro_CodL", "Assunto_CodAs");

                    b.HasIndex("Assunto_CodAs")
                        .HasDatabaseName("Livro_Assunto_FKIndex2");

                    b.HasIndex("Livro_CodL")
                        .HasDatabaseName("Livro_Assunto_FKIndex1");

                    b.ToTable("Livro_Assunto", (string)null);
                });

            modelBuilder.Entity("Livraria.Domain.Entities.LivroAutor", b =>
                {
                    b.Property<int>("Livro_CodL")
                        .HasColumnType("int")
                        .HasColumnName("Livro_CodL");

                    b.Property<int>("Autor_CodAu")
                        .HasColumnType("int")
                        .HasColumnName("Autor_CodAu");

                    b.HasKey("Livro_CodL", "Autor_CodAu");

                    b.HasIndex("Autor_CodAu")
                        .HasDatabaseName("Livro_Autor_FKIndex2");

                    b.HasIndex("Livro_CodL")
                        .HasDatabaseName("Livro_Autor_FKIndex1");

                    b.ToTable("Livro_Autor", (string)null);
                });

            modelBuilder.Entity("Livraria.Domain.Entities.LivroPreco", b =>
                {
                    b.Property<int>("Livro_CodL")
                        .HasColumnType("int")
                        .HasColumnName("Livro_CodL");

                    b.Property<int>("FormaCompra_CodFc")
                        .HasColumnType("int")
                        .HasColumnName("FormaCompra_CodFc");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Valor");

                    b.HasKey("Livro_CodL", "FormaCompra_CodFc");

                    b.HasIndex("FormaCompra_CodFc");

                    b.ToTable("Livro_Preco", (string)null);
                });

            modelBuilder.Entity("Livraria.Domain.Entities.LivroAssunto", b =>
                {
                    b.HasOne("Livraria.Domain.Entities.Assunto", "Assunto")
                        .WithMany("LivroAssuntos")
                        .HasForeignKey("Assunto_CodAs")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Livraria.Domain.Entities.Livro", "Livro")
                        .WithMany("LivroAssuntos")
                        .HasForeignKey("Livro_CodL")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assunto");

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("Livraria.Domain.Entities.LivroAutor", b =>
                {
                    b.HasOne("Livraria.Domain.Entities.Autor", "Autor")
                        .WithMany("LivroAutores")
                        .HasForeignKey("Autor_CodAu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Livraria.Domain.Entities.Livro", "Livro")
                        .WithMany("LivroAutores")
                        .HasForeignKey("Livro_CodL")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("Livraria.Domain.Entities.LivroPreco", b =>
                {
                    b.HasOne("Livraria.Domain.Entities.FormaCompra", "FormaCompra")
                        .WithMany("LivroPrecos")
                        .HasForeignKey("FormaCompra_CodFc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Livraria.Domain.Entities.Livro", "Livro")
                        .WithMany("LivroPrecos")
                        .HasForeignKey("Livro_CodL")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormaCompra");

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("Livraria.Domain.Entities.Assunto", b =>
                {
                    b.Navigation("LivroAssuntos");
                });

            modelBuilder.Entity("Livraria.Domain.Entities.Autor", b =>
                {
                    b.Navigation("LivroAutores");
                });

            modelBuilder.Entity("Livraria.Domain.Entities.FormaCompra", b =>
                {
                    b.Navigation("LivroPrecos");
                });

            modelBuilder.Entity("Livraria.Domain.Entities.Livro", b =>
                {
                    b.Navigation("LivroAssuntos");

                    b.Navigation("LivroAutores");

                    b.Navigation("LivroPrecos");
                });
#pragma warning restore 612, 618
        }
    }
}
